# Configurations for CIFAR10 dataset
# Author : Shikhar Tuli

dataset: CIFAR10

# Dataset directories
data_dir: /scratch/gpfs/stuli/pytorch_datasets/
manual_dir: null

# Training parameters
train_batch_size: 256
test_batch_size: 512 

# Architecture parameters
module_vertices: 3
head_vertices: 6
max_edges: 9
max_modules: 2
base_ops:
  - conv5x5-bn-relu
  - conv3x3-bn-relu
  - conv1x1-bn-relu
  - maxpool3x3
flatten_ops:
  - global-avg-pool
  - flatten
dense_ops:
  - dense-1024
  - dense-4096
  - dropout-p5
  - dropout-p4

# Hash algorithm, one in [md5, sha256, sha512]
hash_algo: sha256