# This is a basic workflow to help you get started with Actions

name: get_todos

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - id: todos
        run: grep -rw './cnnbench/' -e 'TODO' | wc -l
      - name: TODOs badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: todos
          LABEL: 'TODOs'
          STATUS: ${{ steps.todos.outputs.data }}
          COLOR: FFC401
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
